#!/bin/python

import requests
from bs4 import BeautifulSoup
import re

with open('2023', 'r') as f:
	while True:
		url = f.readline() # + '/index.html'
		if url == 0:
			break
		page = requests.get(url, headers={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1"})

		soup = BeautifulSoup(page.content, "html.parser")
		
		film_details = soup.find_all("div", class_="films-details-wrap")
		for detail in film_details:
			film_name = detail.find("h4").b.string
			break
		for film_detail in soup.find_all("div", class_="films-details-wrap"):
			for detail in film_detail.find_all("h4"):
				print(detail) #.find("h4").b.string)
